from __future__ import annotations

from typing import Any, Dict, List


PRODUCT_MULTIPLIERS = {
    "CNC": 1.0,
    "BTST": 0.72,
    "MIS": 0.45,
    "NRML": 1.0,
}


SCENARIO_TEMPLATES = {
    "index_future": [
        -1.00,
        -0.92,
        -0.82,
        -0.70,
        -0.58,
        -0.42,
        -0.24,
        -0.08,
        0.10,
        0.25,
        0.42,
        0.58,
        0.72,
        0.85,
        0.94,
        1.00,
    ],
    "stock_future": [
        -1.00,
        -0.93,
        -0.84,
        -0.73,
        -0.60,
        -0.45,
        -0.27,
        -0.09,
        0.11,
        0.29,
        0.46,
        0.62,
        0.76,
        0.88,
        0.96,
        1.00,
    ],
    "commodity_future": [
        -1.00,
        -0.90,
        -0.78,
        -0.66,
        -0.52,
        -0.38,
        -0.20,
        -0.06,
        0.12,
        0.28,
        0.44,
        0.60,
        0.74,
        0.86,
        0.95,
        1.00,
    ],
    "agri_future": [
        -1.00,
        -0.88,
        -0.76,
        -0.62,
        -0.48,
        -0.34,
        -0.18,
        -0.04,
        0.11,
        0.24,
        0.38,
        0.54,
        0.70,
        0.82,
        0.92,
        1.00,
    ],
    "long_call": [
        -1.00,
        -0.97,
        -0.92,
        -0.85,
        -0.76,
        -0.63,
        -0.48,
        -0.26,
        0.02,
        0.26,
        0.48,
        0.66,
        0.80,
        0.91,
        0.98,
        1.02,
    ],
    "long_put": [
        1.00,
        0.95,
        0.88,
        0.78,
        0.66,
        0.52,
        0.35,
        0.14,
        -0.08,
        -0.25,
        -0.40,
        -0.56,
        -0.70,
        -0.82,
        -0.92,
        -1.00,
    ],
}


EXCHANGES = [
    {
        "code": "NSE",
        "name": "National Stock Exchange",
        "clearing": "NSE Clearing",
        "accent": "var(--nse)",
        "focus": "Equity cash, index derivatives, stock derivatives, currency derivatives",
    },
    {
        "code": "BSE",
        "name": "BSE Limited",
        "clearing": "ICCL",
        "accent": "var(--bse)",
        "focus": "Equity cash and BSE derivatives such as SENSEX and BANKEX",
    },
    {
        "code": "MCX",
        "name": "Multi Commodity Exchange",
        "clearing": "MCX Clearing model",
        "accent": "var(--mcx)",
        "focus": "Energy, bullion, and base metal commodity derivatives",
    },
    {
        "code": "NCDEX",
        "name": "National Commodity & Derivatives Exchange",
        "clearing": "NCCL",
        "accent": "var(--ncdex)",
        "focus": "Agri commodity derivatives cleared through National Commodity Clearing Limited",
    },
]


def _span_contract(
    contract_id: str,
    exchange: str,
    clearing_corp: str,
    symbol: str,
    display_name: str,
    instrument_type: str,
    option_type: str | None,
    underlying: str,
    expiry_label: str,
    unit_label: str,
    lot_size: int,
    last_price: float,
    span_per_lot: float,
    exposure_pct: float,
    additional_pct: float,
    delivery_pct: float,
    short_option_min: float,
    product_types: List[str],
    scenario_template: str,
) -> Dict[str, Any]:
    return {
        "id": contract_id,
        "exchange": exchange,
        "clearingCorp": clearing_corp,
        "segment": "DERIVATIVES",
        "instrumentType": instrument_type,
        "optionType": option_type or "",
        "symbol": symbol,
        "displayName": display_name,
        "underlying": underlying,
        "expiryLabel": expiry_label,
        "unitLabel": unit_label,
        "lotSize": lot_size,
        "currency": "INR",
        "lastPrice": last_price,
        "riskStyle": "SPAN",
        "spanPerLot": span_per_lot,
        "exposurePct": exposure_pct,
        "additionalPct": additional_pct,
        "deliveryPct": delivery_pct,
        "shortOptionMinPerLot": short_option_min,
        "productTypes": product_types,
        "scenarioTemplate": scenario_template,
    }


def _cash_contract(
    contract_id: str,
    exchange: str,
    clearing_corp: str,
    symbol: str,
    display_name: str,
    last_price: float,
    var_pct: float,
    elm_pct: float,
    adhoc_pct: float,
    product_types: List[str],
) -> Dict[str, Any]:
    return {
        "id": contract_id,
        "exchange": exchange,
        "clearingCorp": clearing_corp,
        "segment": "CASH",
        "instrumentType": "EQUITY",
        "optionType": "",
        "symbol": symbol,
        "displayName": display_name,
        "underlying": symbol,
        "expiryLabel": "Cash Market",
        "unitLabel": "shares",
        "lotSize": 1,
        "currency": "INR",
        "lastPrice": last_price,
        "riskStyle": "VAR_ELM",
        "varPct": var_pct,
        "elmPct": elm_pct,
        "adhocPct": adhoc_pct,
        "productTypes": product_types,
    }


CONTRACTS = [
    _span_contract(
        contract_id="nse-nifty-fut",
        exchange="NSE",
        clearing_corp="NSE Clearing",
        symbol="NIFTY",
        display_name="NSE NIFTY 50 Futures Apr",
        instrument_type="FUTURE",
        option_type=None,
        underlying="NIFTY 50",
        expiry_label="Apr 2026",
        unit_label="lots",
        lot_size=65,
        last_price=23151.1,
        span_per_lot=109171.32,
        exposure_pct=3.5,
        additional_pct=0.6,
        delivery_pct=0.0,
        short_option_min=0.0,
        product_types=["NRML", "MIS"],
        scenario_template="index_future",
    ),
    _span_contract(
        contract_id="nse-nifty-next-fut",
        exchange="NSE",
        clearing_corp="NSE Clearing",
        symbol="NIFTY",
        display_name="NSE NIFTY 50 Futures May",
        instrument_type="FUTURE",
        option_type=None,
        underlying="NIFTY 50",
        expiry_label="May 2026",
        unit_label="lots",
        lot_size=50,
        last_price=22596.0,
        span_per_lot=94200.0,
        exposure_pct=3.5,
        additional_pct=0.5,
        delivery_pct=0.0,
        short_option_min=0.0,
        product_types=["NRML", "MIS"],
        scenario_template="index_future",
    ),
    _span_contract(
        contract_id="nse-banknifty-call",
        exchange="NSE",
        clearing_corp="NSE Clearing",
        symbol="BANKNIFTY",
        display_name="NSE BANKNIFTY 52000 CE",
        instrument_type="OPTION",
        option_type="CALL",
        underlying="BANKNIFTY",
        expiry_label="Apr 2026",
        unit_label="lots",
        lot_size=15,
        last_price=522.0,
        span_per_lot=124000.0,
        exposure_pct=2.6,
        additional_pct=0.4,
        delivery_pct=0.0,
        short_option_min=42000.0,
        product_types=["NRML", "MIS"],
        scenario_template="long_call",
    ),
    _span_contract(
        contract_id="nse-reliance-fut",
        exchange="NSE",
        clearing_corp="NSE Clearing",
        symbol="RELIANCE",
        display_name="NSE RELIANCE Futures",
        instrument_type="FUTURE",
        option_type=None,
        underlying="RELIANCE",
        expiry_label="Apr 2026",
        unit_label="lots",
        lot_size=500,
        last_price=1308.9,
        span_per_lot=76803.0,
        exposure_pct=5.0,
        additional_pct=1.0,
        delivery_pct=0.0,
        short_option_min=0.0,
        product_types=["NRML", "MIS"],
        scenario_template="stock_future",
    ),
    _cash_contract(
        contract_id="nse-reliance-cash",
        exchange="NSE",
        clearing_corp="NSE Clearing",
        symbol="RELIANCE",
        display_name="NSE RELIANCE Equity",
        last_price=2934.0,
        var_pct=18.0,
        elm_pct=3.5,
        adhoc_pct=0.0,
        product_types=["CNC", "MIS", "BTST"],
    ),
    _span_contract(
        contract_id="bse-sensex-fut",
        exchange="BSE",
        clearing_corp="ICCL",
        symbol="SENSEX",
        display_name="BSE SENSEX Futures",
        instrument_type="FUTURE",
        option_type=None,
        underlying="SENSEX",
        expiry_label="Apr 2026",
        unit_label="lots",
        lot_size=10,
        last_price=74480.0,
        span_per_lot=64000.0,
        exposure_pct=3.0,
        additional_pct=0.5,
        delivery_pct=0.0,
        short_option_min=0.0,
        product_types=["NRML", "MIS"],
        scenario_template="index_future",
    ),
    _span_contract(
        contract_id="bse-bankex-put",
        exchange="BSE",
        clearing_corp="ICCL",
        symbol="BANKEX",
        display_name="BSE BANKEX 60000 PE",
        instrument_type="OPTION",
        option_type="PUT",
        underlying="BANKEX",
        expiry_label="Apr 2026",
        unit_label="lots",
        lot_size=15,
        last_price=410.0,
        span_per_lot=93000.0,
        exposure_pct=2.3,
        additional_pct=0.4,
        delivery_pct=0.0,
        short_option_min=28000.0,
        product_types=["NRML", "MIS"],
        scenario_template="long_put",
    ),
    _cash_contract(
        contract_id="bse-tcs-cash",
        exchange="BSE",
        clearing_corp="ICCL",
        symbol="TCS",
        display_name="BSE TCS Equity",
        last_price=4085.0,
        var_pct=16.0,
        elm_pct=3.5,
        adhoc_pct=0.0,
        product_types=["CNC", "MIS", "BTST"],
    ),
    _span_contract(
        contract_id="mcx-crudeoil-fut",
        exchange="MCX",
        clearing_corp="MCX Clearing model",
        symbol="CRUDEOIL",
        display_name="MCX Crude Oil Futures",
        instrument_type="FUTURE",
        option_type=None,
        underlying="CRUDEOIL",
        expiry_label="May 2026",
        unit_label="lots",
        lot_size=100,
        last_price=6725.0,
        span_per_lot=62000.0,
        exposure_pct=1.8,
        additional_pct=0.8,
        delivery_pct=0.2,
        short_option_min=0.0,
        product_types=["NRML", "MIS"],
        scenario_template="commodity_future",
    ),
    _span_contract(
        contract_id="mcx-gold-fut",
        exchange="MCX",
        clearing_corp="MCX Clearing model",
        symbol="GOLD",
        display_name="MCX Gold Futures",
        instrument_type="FUTURE",
        option_type=None,
        underlying="GOLD",
        expiry_label="Jun 2026",
        unit_label="lots",
        lot_size=100,
        last_price=72150.0,
        span_per_lot=88000.0,
        exposure_pct=2.0,
        additional_pct=0.5,
        delivery_pct=0.2,
        short_option_min=0.0,
        product_types=["NRML", "MIS"],
        scenario_template="commodity_future",
    ),
    _span_contract(
        contract_id="mcx-silver-call",
        exchange="MCX",
        clearing_corp="MCX Clearing model",
        symbol="SILVER",
        display_name="MCX Silver 90000 CE",
        instrument_type="OPTION",
        option_type="CALL",
        underlying="SILVER",
        expiry_label="Jun 2026",
        unit_label="lots",
        lot_size=30,
        last_price=1840.0,
        span_per_lot=76000.0,
        exposure_pct=1.4,
        additional_pct=0.4,
        delivery_pct=0.15,
        short_option_min=22000.0,
        product_types=["NRML"],
        scenario_template="long_call",
    ),
    _span_contract(
        contract_id="ncdex-soybean-fut",
        exchange="NCDEX",
        clearing_corp="NCCL",
        symbol="SOYBEAN",
        display_name="NCDEX Soybean Futures",
        instrument_type="FUTURE",
        option_type=None,
        underlying="SOYBEAN",
        expiry_label="May 2026",
        unit_label="lots",
        lot_size=100,
        last_price=4850.0,
        span_per_lot=34500.0,
        exposure_pct=1.2,
        additional_pct=0.8,
        delivery_pct=0.3,
        short_option_min=0.0,
        product_types=["NRML"],
        scenario_template="agri_future",
    ),
    _span_contract(
        contract_id="ncdex-guarseed-fut",
        exchange="NCDEX",
        clearing_corp="NCCL",
        symbol="GUARSEED",
        display_name="NCDEX Guarseed Futures",
        instrument_type="FUTURE",
        option_type=None,
        underlying="GUARSEED",
        expiry_label="May 2026",
        unit_label="lots",
        lot_size=100,
        last_price=5620.0,
        span_per_lot=36200.0,
        exposure_pct=1.3,
        additional_pct=0.9,
        delivery_pct=0.4,
        short_option_min=0.0,
        product_types=["NRML"],
        scenario_template="agri_future",
    ),
]


CONTRACT_MAP = {contract["id"]: contract for contract in CONTRACTS}


SAMPLE_PORTFOLIOS = {
    "diversified": {
        "name": "Diversified India Basket",
        "description": "Cross-market mix across NSE, BSE, MCX, and NCDEX with index, stock, commodity, and agri risk.",
        "positions": [
            {"contractId": "nse-nifty-fut", "productType": "NRML", "side": "BUY", "quantity": 1, "price": 22510.0},
            {"contractId": "nse-nifty-next-fut", "productType": "NRML", "side": "SELL", "quantity": 1, "price": 22596.0},
            {"contractId": "nse-banknifty-call", "productType": "NRML", "side": "SELL", "quantity": 1, "price": 522.0},
            {"contractId": "nse-reliance-cash", "productType": "CNC", "side": "BUY", "quantity": 140, "price": 2934.0},
            {"contractId": "bse-sensex-fut", "productType": "MIS", "side": "SELL", "quantity": 2, "price": 74480.0},
            {"contractId": "mcx-crudeoil-fut", "productType": "NRML", "side": "BUY", "quantity": 3, "price": 6725.0},
            {"contractId": "ncdex-soybean-fut", "productType": "NRML", "side": "SELL", "quantity": 2, "price": 4850.0},
        ],
    },
    "commodity_hedge": {
        "name": "Commodity Hedge Book",
        "description": "MCX and NCCL-style commodity risk with outright and spread-like futures exposure.",
        "positions": [
            {"contractId": "mcx-gold-fut", "productType": "NRML", "side": "BUY", "quantity": 1, "price": 72150.0},
            {"contractId": "mcx-crudeoil-fut", "productType": "MIS", "side": "SELL", "quantity": 2, "price": 6725.0},
            {"contractId": "mcx-silver-call", "productType": "NRML", "side": "SELL", "quantity": 1, "price": 1840.0},
            {"contractId": "ncdex-guarseed-fut", "productType": "NRML", "side": "BUY", "quantity": 1, "price": 5620.0},
        ],
    },
    "zerodha_validation": {
        "name": "Zerodha Validation Set",
        "description": "Two single-leg contracts calibrated to match Zerodha's live April 6, 2026 futures margin totals for quick validation.",
        "positions": [
            {"contractId": "nse-nifty-fut", "productType": "NRML", "side": "BUY", "quantity": 1, "price": 23151.1},
            {"contractId": "nse-reliance-fut", "productType": "NRML", "side": "BUY", "quantity": 1, "price": 1308.9},
        ],
    },
}


METHOD_NOTES = [
    {
        "title": "Equity cash",
        "body": "Modeled using VaR, Extreme Loss Margin, and optional ad hoc percentage blocks with broker-style product multipliers for CNC, BTST, and MIS.",
    },
    {
        "title": "Index, stock, and commodity derivatives",
        "body": "Modeled as SPAN-style scan risk from 16 scenarios plus exchange-style exposure, additional, delivery, and short-option floor components.",
    },
    {
        "title": "Hedge and spread benefit",
        "body": "Netting is applied within exchange and underlying groups via scenario aggregation, which produces a hedge benefit when opposing positions offset risk.",
    },
]


OFFICIAL_REFERENCES = [
    {
        "label": "NSE Margin Calculator",
        "url": "https://www.nseindia.com/market-data/margin-calculator",
    },
    {
        "label": "BSE Risk & Margin Overview",
        "url": "https://www.bseindia.com/static/fpi/TradingSettlement.aspx",
    },
    {
        "label": "NCCL Clearing Overview",
        "url": "https://www.nccl.co.in/public/assets/circulars/margins_on_steel_long_futures_contract_steel_13012021.pdf",
    },
    {
        "label": "NCDEX Overview",
        "url": "https://ncdex.com/",
    },
]


WORKBOOK_SECTIONS = [
    {
        "title": "Margin stack",
        "summary": "How the top-line requirement is assembled in NCCL CAL.",
        "points": [
            "Total margin = derivatives requirement + cash margin.",
            "Derivatives requirement = net SPAN scan loss + exposure/additional/delivery blocks, subject to short-option floor where applicable.",
            "Blocked funds = total margin + premium payable on long options.",
            "Premium receivable on short options is shown separately because brokers usually reflect it as a receivable and not as margin itself.",
        ],
    },
    {
        "title": "Cash equity methodology",
        "summary": "Modeled in the style of Indian broker cash-market requirement logic.",
        "points": [
            "Cash notional = quantity x traded price.",
            "Cash margin = (VaR + ELM + ad hoc percentage blocks) x product multiplier.",
            "CNC carries the full modeled block, while BTST and MIS apply reduced multipliers in this project to simulate lower upfront broker blocks.",
        ],
    },
    {
        "title": "Derivative methodology",
        "summary": "SPAN-like scan logic inspired by Indian broker and clearing workflows.",
        "points": [
            "Each derivative preset contains a 16-scenario scan template and a span-per-lot reference value in INR.",
            "Scenario P/L is aggregated across positions within the same exchange and underlying group.",
            "Net SPAN is the absolute value of the worst grouped scenario loss after offsets.",
            "Exposure, additional margin, and delivery margin are then added over and above the net scan risk.",
        ],
    },
    {
        "title": "Spread and hedge benefit",
        "summary": "Why opposite legs reduce the margin block.",
        "points": [
            "Gross SPAN is the sum of standalone scan losses for each derivative position before any offset.",
            "Net SPAN is the grouped worst-case scan loss after long and short positions in the same underlying offset each other.",
            "Spread benefit = gross SPAN - net SPAN.",
            "The bundled diversified sample includes long and short NIFTY futures expiries so the benefit is visible immediately.",
        ],
    },
    {
        "title": "Interpretation guide",
        "summary": "How to read the output quickly like a broker margin screen.",
        "points": [
            "Span is the core scenario-based risk block.",
            "Exposure margin is the add-on bucket covering non-scan risk buffers such as exposure, additional, and delivery style charges.",
            "Premium receivable and premium payable reflect option cash-flow treatment.",
            "Total margin is the clearest estimate of funds required before taking or carrying the basket.",
        ],
    },
]


def get_bootstrap_payload() -> Dict[str, Any]:
    return {
        "brand": {
            "name": "NCCL CAL",
            "tagline": "Indian Broker Margin Studio",
            "baseCurrency": "INR",
        },
        "productMultipliers": PRODUCT_MULTIPLIERS,
        "exchanges": EXCHANGES,
        "contracts": CONTRACTS,
        "samplePortfolios": SAMPLE_PORTFOLIOS,
        "methodNotes": METHOD_NOTES,
        "officialReferences": OFFICIAL_REFERENCES,
        "workbookSections": WORKBOOK_SECTIONS,
    }
